name: rocket
description: "Aim High, Reach Higher"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  lottie: ^3.1.2
  animated_splash_screen: ^1.3.0
  page_transition: ^2.1.0
  flutter_bloc: ^8.1.6
  cupertino_icons: ^1.0.2 
  iconsax: ^0.0.8
  flutter_chat_ui: ^1.6.15
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/lottie/backgrounds/
    - assets/lottie/loadings/
    - assets/logos/
    - assets/backgrounds/
    - assets/images/player.png
    - assets/images/enemy.png
